#include "stm32f4xx.h"
#include "stm32f407xx.h"


void Encoder_ini(void){
	
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	RCC->AHB1ENR |=RCC_AHB1ENR_GPIOAEN;
	
	GPIOA->MODER &=~GPIO_MODER_MODER0_0|GPIO_MODER_MODER1_0;
	GPIOA->MODER |=GPIO_MODER_MODER0_1|GPIO_MODER_MODER1_1;
	GPIOA->PUPDR &=~GPIO_PUPDR_PUPDR0_1|GPIO_PUPDR_PUPDR1_1|GPIO_PUPDR_PUPDR0_0|GPIO_PUPDR_PUPDR1_0;
	GPIOA->OSPEEDR |=GPIO_OSPEEDER_OSPEEDR0_0|GPIO_OSPEEDER_OSPEEDR1_0|GPIO_OSPEEDER_OSPEEDR0_1|GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOA->AFR[0]=0x22;
	
	TIM5->CCMR1 |=TIM_CCMR1_IC1F|TIM_CCMR1_IC2F;
	TIM5->CCER &=~(TIM_CCER_CC1P|TIM_CCER_CC2P);
	TIM5->SMCR |=TIM_SMCR_SMS_0|TIM_SMCR_SMS_1;
	TIM5->ARR=0x64;
	TIM5->CR1 |=TIM_CR1_CEN;
	TIM5->CNT=0x0;
}
