#ifndef GPIO_INI_H
#define GPIO_INI_H

#include "stm32f4xx.h" 
#include "gpio_ini.h"

#define D15ON GPIOD->BSRR=GPIO_BSRR_BS_15;
#define D15OFF GPIOD->BSRR=GPIO_BSRR_BR_15;
#define D14ON GPIOD->BSRR=GPIO_BSRR_BS_14;
#define D14OFF GPIOD->BSRR=GPIO_BSRR_BR_14;
#define D13ON GPIOD->BSRR=GPIO_BSRR_BS_13;
#define D13OFF GPIOD->BSRR=GPIO_BSRR_BR_13;
#define D12ON GPIOD->BSRR=GPIO_BSRR_BS_12;
#define D12OFF GPIOD->BSRR=GPIO_BSRR_BR_12;
#define D11ON GPIOD->BSRR=GPIO_BSRR_BS_11;
#define D11OFF GPIOD->BSRR=GPIO_BSRR_BR_11;
#define D10ON GPIOD->BSRR=GPIO_BSRR_BS_10;
#define D10OFF GPIOD->BSRR=GPIO_BSRR_BR_10;
#define D9ON GPIOD->BSRR=GPIO_BSRR_BS_9;
#define D9OFF GPIOD->BSRR=GPIO_BSRR_BR_9;
#define D8ON GPIOD->BSRR=GPIO_BSRR_BS_8;
#define D8OFF GPIOD->BSRR=GPIO_BSRR_BR_8;
#define D7ON GPIOD->BSRR=GPIO_BSRR_BS_7;
#define D7OFF GPIOD->BSRR=GPIO_BSRR_BR_7;
#define D6ON GPIOD->BSRR=GPIO_BSRR_BS_6;
#define D6OFF GPIOD->BSRR=GPIO_BSRR_BR_6;
#define D5ON GPIOD->BSRR=GPIO_BSRR_BS_5;
#define D5OFF GPIOD->BSRR=GPIO_BSRR_BR_5;
#define D4ON GPIOD->BSRR=GPIO_BSRR_BS_4;
#define D4OFF GPIOD->BSRR=GPIO_BSRR_BR_4;
#define D3ON GPIOD->BSRR=GPIO_BSRR_BS_3;
#define D3OFF GPIOD->BSRR=GPIO_BSRR_BR_3;
#define D2ON GPIOD->BSRR=GPIO_BSRR_BS_2;
#define D2OFF GPIOD->BSRR=GPIO_BSRR_BR_2;
#define D1ON GPIOD->BSRR=GPIO_BSRR_BS_1;
#define D1OFF GPIOD->BSRR=GPIO_BSRR_BR_1;
#define D0ON GPIOD->BSRR=GPIO_BSRR_BS_0;
#define D0OFF GPIOD->BSRR=GPIO_BSRR_BR_0;

void LEDs_ini(void);
void Button_ini(void);









#endif

